// Common amenities for properties
export const AMENITIES = [
  'wifi',
  'pool',
  'spa',
  'gym',
  'kitchen',
  'air-conditioning',
  'heating',
  'parking',
  'beach-access',
  'mountain-view',
  'ocean-view',
  'garden',
  'terrace',
  'balcony',
  'fireplace',
  'hot-tub',
  'sauna',
  'pet-friendly',
  'laundry',
  'concierge',
  'room-service',
  'restaurant',
  'bar',
  'kids-friendly',
  'wheelchair-accessible',
] as const;

export type Amenity = typeof AMENITIES[number];

// Amenity icons mapping (using lucide icon names)
export const AMENITY_ICONS: Record<Amenity, string> = {
  'wifi': 'Wifi',
  'pool': 'Waves',
  'spa': 'Sparkles',
  'gym': 'Dumbbell',
  'kitchen': 'ChefHat',
  'air-conditioning': 'Wind',
  'heating': 'Flame',
  'parking': 'Car',
  'beach-access': 'Umbrella',
  'mountain-view': 'Mountain',
  'ocean-view': 'Ship',
  'garden': 'Flower2',
  'terrace': 'TreeDeciduous',
  'balcony': 'Home',
  'fireplace': 'Flame',
  'hot-tub': 'Bath',
  'sauna': 'Thermometer',
  'pet-friendly': 'PawPrint',
  'laundry': 'WashingMachine',
  'concierge': 'Bell',
  'room-service': 'UtensilsCrossed',
  'restaurant': 'UtensilsCrossed',
  'bar': 'Wine',
  'kids-friendly': 'Baby',
  'wheelchair-accessible': 'Accessibility',
};

// Amenity display labels
export const AMENITY_LABELS: Record<Amenity, string> = {
  'wifi': 'WiFi',
  'pool': 'Swimming Pool',
  'spa': 'Spa & Wellness',
  'gym': 'Fitness Center',
  'kitchen': 'Full Kitchen',
  'air-conditioning': 'Air Conditioning',
  'heating': 'Central Heating',
  'parking': 'Free Parking',
  'beach-access': 'Beach Access',
  'mountain-view': 'Mountain View',
  'ocean-view': 'Ocean View',
  'garden': 'Private Garden',
  'terrace': 'Terrace',
  'balcony': 'Balcony',
  'fireplace': 'Fireplace',
  'hot-tub': 'Hot Tub',
  'sauna': 'Sauna',
  'pet-friendly': 'Pet Friendly',
  'laundry': 'Laundry',
  'concierge': '24/7 Concierge',
  'room-service': 'Room Service',
  'restaurant': 'On-site Restaurant',
  'bar': 'Bar & Lounge',
  'kids-friendly': 'Kids Friendly',
  'wheelchair-accessible': 'Wheelchair Accessible',
};

// Popular destinations (for homepage)
export const POPULAR_DESTINATIONS = [
  { name: 'Tuscany', country: 'Italy', image: '' },
  { name: 'Santorini', country: 'Greece', image: '' },
  { name: 'Bali', country: 'Indonesia', image: '' },
  { name: 'Maldives', country: 'Maldives', image: '' },
  { name: 'French Riviera', country: 'France', image: '' },
  { name: 'Amalfi Coast', country: 'Italy', image: '' },
];
