project_id = "xavjbiuhcmupsoocrmhf"

[functions.advancecm-sync]
verify_jwt = false

[functions.pms-sync-cron]
verify_jwt = false

[functions.pms-webhook]
verify_jwt = false

[functions.seasonal-rates-import]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.scheduled-posts-cron]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.website-analytics]
verify_jwt = false
